org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap_rechiseled_create
addon_name=BlueMap Rechiseled Create Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-rechiseled-create-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=209444
accepted_jar_sha256=651b8be8a41d459f04f3ec1cbc64ba7441cceb3c2bb3c07d518556a11c83596b
