# Generated by gallery/generate.py; do not edit.
function rechiseledcreate_gallery:verify
scoreboard players operation #100t_failures rc_gallery = #failures rc_gallery
scoreboard players operation #100t_checked rc_gallery = #checked rc_gallery
tellraw @a [{"text":"Rechiseled: Create gallery 100t: "},{"score":{"name":"#100t_checked","objective":"rc_gallery"}},{"text":" block checks, "},{"score":{"name":"#100t_failures","objective":"rc_gallery"}},{"text":" failures"}]
