# Generated by gallery/generate.py; do not edit.
function rechiseledcreate_gallery:verify
scoreboard players operation #20t_failures rc_gallery = #failures rc_gallery
scoreboard players operation #20t_checked rc_gallery = #checked rc_gallery
