# Generated by gallery/generate.py; do not edit.
function rechiseledcreate_gallery:verify
scoreboard players operation #immediate_failures rc_gallery = #failures rc_gallery
scoreboard players operation #immediate_checked rc_gallery = #checked rc_gallery
tellraw @a [{"text":"Rechiseled: Create gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"rc_gallery"}},{"text":" block checks, "},{"score":{"name":"#immediate_failures","objective":"rc_gallery"}},{"text":" failures"}]
