## Bounded, disposable Rechiseled: Create review map.

world: "world"
dimension: "minecraft:overworld"
name: "Rechiseled: Create review"

start-pos: { x: 208, z: 208 }

render-mask: [
  {
    min-x: 160
    max-x: 255
    min-z: 160
    max-z: 255
    min-y: 99
    max-y: 132
  }
]

storage: "file"
